stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv sequential-auctions-on-gpu
    - source sequential-auctions-on-gpu/bin/activate
    - pip install -r requirements.txt
    - pytest --cov-report term-missing --junitxml=report.xml

pages:
  stage: deploy
  before_script:
    - pip install virtualenv
    - virtualenv sequential-auctions-on-gpu
    - source sequential-auctions-on-gpu/bin/activate
    - pip install -r requirements.txt
    - pip install sphinx==6.2.1 furo==2023.7.26 myst-parser==2.0.0
  script:
    - cd docs
    - make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
