stages:
  - install_env
  - test

install_env:
  stage: install_env
  script:
  - pip install virtualenv
  - virtualenv sequential-auctions-on-gpu
  - source sequential-auctions-on-gpu/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - source ./sequential-auctions-on-gpu/bin/activate
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: testreport.xml
    expire_in: 6 months
