policy: "MlpPolicy"
n_rollout_steps: 16
gamma: 1.0
translate_action_spaces_for_agents: None
translate_observation_spaces_for_agents: None
action_space_translator: "identity"
observation_space_translator: "identity"