policy: "MlpPolicy"
n_rollout_steps: 256
gamma: 0.99
gradient_steps: -1
batch_size: 8096
tau: 1.0
learning_rate: 0.0001
buffer_size: 50_000_000
learning_starts: 50_000_000
target_update_interval: 50_000_000
exploration_fraction: 0.1
exploration_initial_eps: 1.0
exploration_final_eps: 0.05