net_arch:  # No. of layers and neurons
  pi: [32, 32]
  vf: [32, 32]
activation_fn: nn.SELU  # Activation function for inner neurons
action_activation_fn: null  # activation function on output (action)
action_dependent_std: false  # SB3 only learns a fixed std in output (independent of observation)