net_arch:  # No. of layers and neurons
  pi: [64, 64]
  vf: [64, 64]
activation_fn: nn.SELU  # Activation function for inner neurons
action_activation_fn: None  # activation function on output (action),
# any torch activation function, e.g., nn.Sigmoid or one of the following custom ones:[Abs]
action_dependent_std: false  # SB3 only learns a fixed std in output (independent of observation)
log_std_init: -3.0  # The initial log_std_dev larger values mean larger std_dev 