net_arch:  # No. of layers and neurons
  pi: [32, 16, 4]
  vf: [32, 16, 4]
activation_fn: nn.ELU  # Activation function for inner neurons
action_activation_fn: null  # activation function on output (action)
action_dependent_std: true  # SB3 only learns a fixed std in output (independent of observation)