# @package _global_

algorithm_configs:
  ppo:
    n_rollout_steps: 25
    learning_rate: 1e-3
    gamma: 0.99
    full_batch_updates: false
    feature_extractor: "flatten" # "flatten" and "customCNN"