
valid_envs: ["rockpaperscissors", "sequential_auction", "signaling_contest", "simple_soccer"]
log_path: './logs/'
experiment_log_path: ''
experiment_name: ''
device: 6
num_envs: 8000
eval_freq: 200
iteration_num: 5000
total_training_steps: null
n_steps_per_iteration: null
algorithms: ["ppo", "ppo", "ppo", "soccer_handcrafted", "soccer_handcrafted", "soccer_handcrafted"]
policy_sharing: false
defaults:
  - rl_envs: simple_soccer
  - algorithm_configs: all_algos
  - _self_
