
valid_envs: ["rockpaperscissors", "sequential_auction", "signaling_contest", "simple_soccer"]
log_path: './logs/'
experiment_log_path: ''
experiment_name: ''
device: 1
num_envs: 8000
eval_freq: 400
iteration_num: 3200
total_training_steps: null
n_steps_per_iteration: null
algorithms: ["soccer_goal_wall", "ppo", "ppo", "soccer_goal_wall", "soccer_goal_wall", "soccer_goal_wall"]
policy_sharing: false
defaults:
  - rl_envs: simple_soccer
  - algorithm_configs: all_algos
  - _self_
