
valid_envs: ["rockpaperscissors", "sequential_auction", "signaling_contest", "simple_soccer"]
log_path: './logs/'
experiment_log_path: ''
experiment_name: ''
device: 2
num_envs: 64_000
eval_freq: 100
iteration_num: 2000
total_training_steps: null
n_steps_per_iteration: null
algorithms: ["dqn", "soccer_goal_wall"]
policy_sharing: false
defaults:
  - rl_envs: simple_soccer
  - algorithm_configs: all_algos
  - _self_
