
valid_envs: ["rockpaperscissors", "sequential_auction", "signaling_contest", "simple_soccer"]
log_path: './logs/'
experiment_log_path: ''
experiment_name: ''
delete_logs_after_training: false
device: 1
seed: 0
num_envs: 8_192
eval_freq: 400
verify_br: false
iteration_num: 1000
total_training_steps: null
n_steps_per_iteration: null
algorithms: "ppo"
policy_sharing: false
defaults:
  - rl_envs: sequential_auction
  - algorithm_configs: all_algos
  - space_translators: default_config
  - verifier: default_verifier
  - _self_
