name: "all_algos"
defaults:
  - ppo: ppo_for_soccer
  - reinforce: reinforce
  - rps_single_action: rps_rock
  - soccer_chase_ball: chase_ball_policy
  - soccer_goal_wall: goal_wall_policy
  - soccer_block: block_policy
  - soccer_handcrafted: handcrafted_policy
  - dqn: dqn_for_rps
