name: "sequential_auction"
num_agents: 3
num_rounds_to_play: 2
action_size: 1
valuation_size: 1
available_mechanism_types: ["first", "second"]
mechanism_type: "first"
reduced_observation_space: true
collapse_symmetric_opponents: false