name: "sequential_auction"
num_agents: 3
num_stages: 2
valuation_size: 1
available_mechanism_types: ["first", "second"]
mechanism_type: "first"
reduced_observation_space: true
collapse_symmetric_opponents: false
risk_aversion: 1.0
prettify_plots: true
budgets: null # Can be null, float value, list of floats
defaults:
  - sampler: symmetric_uniform