name: "signaling_contest"
all_information_cases: ["true_valuations", "winning_bids"]
information_case: "true_valuations"
sample_tullock_allocations: false
risk_aversion: 1.0
num_agents: 4
valuation_size: 1
impact_factor: 1.0
use_valuation: true
defaults:
  - sampler: symmetric_uniform
  - sampler/non_default: standard_setting_contest