name: "signaling_contest"
all_information_cases: ["winners_signal", "winning_bids"]
information_case: "winners_signal"
sample_tullock_allocations: false
risk_aversion: 1.0
num_agents: 4
valuation_size: 1
impact_factor: 1.0
use_valuation: true
defaults:
  - sampler: symmetric_uniform
  - optional sampler/non_default: ${rl_envs/sampler}_for_${rl_envs}